import { describe, it, expect } from 'vitest';
import { toJulianDay } from '@/lib/ephemeris/julian';
import { calcPlanet, calcKetu, PLANET_IDS } from '@/lib/ephemeris/swisseph';
import { calcLagna } from '@/lib/charts/lagna';
import fixtures from './fixtures/pyjhora-golden.json';

/**
 * Calibration parity tests against PyJHora (the verified Python port of
 * Jagannatha Hora, ~6800 tests against JHora itself).
 *
 * Fixtures are generated by calc-service/generate_fixtures.py in two modes:
 *  - apparent_mean : apparent positions + mean node — what this TS engine
 *    computes today (Thai preset). Asserted here.
 *  - true_truenode : true geometric positions + true node — JHora's defaults
 *    (Vedic preset). Asserted once the settings model lands; until then the
 *    fixture documents the target values.
 *
 * Tolerances: planets 0.7" (light-time-free quantities agree to ~1e-6°),
 * ascendant 0.005° (PyJHora rounds house cusps slightly differently).
 */

const PLANET_TOL_DEG = 0.0002; // ≈ 0.7 arcsec
const ASC_TOL_DEG = 0.005;

type FixtureChart = (typeof fixtures)['charts'][number];

describe('PyJHora parity — apparent positions + mean node (current engine / Thai preset)', () => {
  for (const chart of fixtures.charts as FixtureChart[]) {
    describe(chart.id, () => {
      const jd = toJulianDay(chart.input);
      const expected = chart.modes.apparent_mean;

      it('matches all planet longitudes', () => {
        for (const [key, id] of Object.entries(PLANET_IDS)) {
          if (key === 'URANUS') continue; // not in PyJHora fixture set
          const got = calcPlanet(id, jd).longitude;
          const want = expected.planets[key as keyof typeof expected.planets];
          expect(Math.abs(got - want), `${key} got=${got} want=${want}`).toBeLessThan(PLANET_TOL_DEG);
        }
      });

      it('matches Ketu (Rahu + 180°)', () => {
        const rahu = calcPlanet(PLANET_IDS.RAHU, jd).longitude;
        const got = calcKetu(rahu);
        expect(Math.abs(got - expected.planets.KETU)).toBeLessThan(PLANET_TOL_DEG);
      });

      it('matches the ascendant', () => {
        const got = calcLagna(jd, chart.input.latitude, chart.input.longitude);
        expect(Math.abs(got - expected.ascendant)).toBeLessThan(ASC_TOL_DEG);
      });
    });
  }
});
